WIP radiasoft/devops#232: ipykernel is now installed in rscode-ipykernel
radiasoft/container-beamsim-jupyter-base pull request #49
Opened 2021-08-26 16:44 UTC by e-carlin

This is needed so the kernel can be intalled in Sirepo to run
notebooks for the raydata app.

2021-08-26 17:40 UTC, robnagler requested changes
See other comments in https://github.com/radiasoft/download/pull/179

2021-08-26 17:40 UTC, robnagler commented on container-conf/radia-run.sh
> +pyenv shell 'py3'
This may no longer be needed. We only have one pyenv_version in this image, and it really won't work if we have multiple pyenvs, and we assume it all over the place, anyway.

2021-08-26 20:14 UTC, e-carlin commented on container-conf/radia-run.sh
> +pyenv shell 'py3'
311b5fc

2021-08-26 20:14 UTC, e-carlin commented
@robnagler ready for another review.

2021-08-27 13:41 UTC, robnagler approved these changes

2021-08-27 13:42 UTC, merged